language: node_js
node_js:
  - '8'
script:
  - npm run clean
  - npm run test
  - npm run build
  - npm run cover
branches:
  only:
    - master
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"